// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9yiglT7Hb2yTTob-wMrreKpchHU0HqI8',
    appId: '1:428862238264:web:60954bbdbad721818f80cd',
    messagingSenderId: '428862238264',
    projectId: 'campusconnect-7e80c',
    authDomain: 'campusconnect-7e80c.firebaseapp.com',
    storageBucket: 'campusconnect-7e80c.appspot.com',
    measurementId: 'G-HMBXET2HZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxDquWmrDm0igIHYw2HKMVnkqG1pDXGoQ',
    appId: '1:428862238264:android:46710218eada23488f80cd',
    messagingSenderId: '428862238264',
    projectId: 'campusconnect-7e80c',
    storageBucket: 'campusconnect-7e80c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX1U-7wleeziAj5qoFlbnpUYgZ37cWjtA',
    appId: '1:428862238264:ios:586f8ea06095b0578f80cd',
    messagingSenderId: '428862238264',
    projectId: 'campusconnect-7e80c',
    storageBucket: 'campusconnect-7e80c.appspot.com',
    iosBundleId: 'com.example.newcampusconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX1U-7wleeziAj5qoFlbnpUYgZ37cWjtA',
    appId: '1:428862238264:ios:586f8ea06095b0578f80cd',
    messagingSenderId: '428862238264',
    projectId: 'campusconnect-7e80c',
    storageBucket: 'campusconnect-7e80c.appspot.com',
    iosBundleId: 'com.example.newcampusconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9yiglT7Hb2yTTob-wMrreKpchHU0HqI8',
    appId: '1:428862238264:web:6c5b8cf30e5a02528f80cd',
    messagingSenderId: '428862238264',
    projectId: 'campusconnect-7e80c',
    authDomain: 'campusconnect-7e80c.firebaseapp.com',
    storageBucket: 'campusconnect-7e80c.appspot.com',
    measurementId: 'G-3PL4N93FX2',
  );
}
